### ISSUE TITLE
DOTFILES CREDITS 

### ISSUE THREAD

**Issue by raexera** [yorkox0/autoAwesome#1]
hello, first i thank you because you like with my AwesomeWM Dotfiles, i saw you put my whole dotfiles in your [repo](https://github.com/yorkox0/autoAwesome/blob/b74ba020cc243b3a7b27ab30f4776f5e08c8e236/config-s4vi/awesome/rc.lua#L7) and mentioned that dotfiles belong to `you` or `s4vitar` which should be `me`, so if u use my dotfiles and u make projects based at my dotfiles, atleast give me proper credits:)
thanks

- [rxyhn](https://github.com/rxyhn)

**Comment by Bleyom** [comment]
solved 🤙🏼
